# An example of how to use SlicerMorph data in R/geomorph
# to do a simple symmetry analysis

remove(list=ls())
right=c(8, 10, 12, 14, 16, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40)
left=c(9, 11, 13, 15, 17, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41)

paired = cbind(left, right)

source("https://raw.githubusercontent.com/muratmaga/SlicerMorph_Rexamples/main/log_parser.R")

# for the next line, modify it with the path to the analysis.log file generated by SLicerMorph GPA.
# this example uses the gorilla skull LMs dataset that's available in the SampleData (File->Download Sample Data). 
# it is located in the timestamped folder within the output folder prefix specified in GPA module
logs = parser("C:\\temp\\RemoteIO\\Gorilla_Skull_LMs\\2021-02-14_20_31_08\\analysis.log")

library(geomorph)

# In this example, we are using the original LM coordinates 
gpa.symm = bilat.symmetry(A=logs$LM, 
                          ind = logs$ID, 
                          land.pairs = paired, 
                          object.sym = TRUE)
# plot meanshapes
plot(mshape(gpa.symm$symm.shape), main="Symmetric component of Meanshape")
plot(mshape(gpa.symm$asymm.shape), main="Asymmetric component of Meanshape")

pca.symm = gm.prcomp(gpa.symm$symm.shape)
pca.asymm = gm.prcomp(gpa.symm$asymm.shape)

plot(pca.symm$x[,1:2], main="Symm", pch=20)
plot(pca.asymm$x[,1:2], main="Asymm", pch=20)
